# 测试配置文件
# @author <a href="https://github.com/gangzaibbb">李兆港</a>
# 
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ggoj
    username: root
    password: 123456
